# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: BJI - Design Portfolio
email: inglisbrendan39@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my design portfolio. This site contains blogs
  about my hands-on projects and details about
  my research at Lehigh University.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bji219.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: InglisBrendan
github_username:  bji219
linkedin_username: brendan-inglis

# Build settings
theme: minima # <- original theme. Try figs, add headshot
# theme: jekyll-theme-dinky
# remote_theme: pages-themes/dinky@v0.2.0
show_excerpts: true
plugins:
  - jekyll-feed
  - jekyll-remote-theme

# Create default "Front Matter" 
defaults:
-
  scope: 
    path: ""
    type: "post"
  values:
    layout: "post"
    author: Brendan Inglis
    # image: assets/Images/Assembly_Img.PNG # remove later, for testing thumbnails only
    excerpt_separator: "<!--more-->"
    # excerpt: "Your Excerpt Here!"
    # values

# Order of home-page Pages
header_pages:
  - about.markdown
  - Resume.markdown
  - research.markdown
  - school_projects.markdown
  - Music.markdown

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
